<h3><?=printf(_('Анализ метала %1s на %2s'), $this->escape($this->metal->getName()), $this->date->formatDMY())?></h3>
<?php
    echo '<div class="row">';
    foreach ($this->analyzes as $an) {
        echo '<div class="col-sm-3">'.$this->analysisMetal_Panel($an).'</div>';
    }
    echo '</div>';
?>

<?php
    $lisChart=array();
    if (count($this->dataChart)) {
        echo '<div id="chart_div" class="row"></div>';
        foreach ($this->dataChart as $data) {
//            echo $data->getDateFormatDMY().' '.$data->getValue().' - '.$data->getValueFigure()."<br>";
            $lisChart[] = '[new Date("'.$data->getDateFormatGDate().'"),'.Core_Math::roundMoney($data->getValue()).','.Core_Math::roundMoney($data->getValueFigure()).']';
        }
    }
?>


<?php
$this->headScript()->prependFile('https://www.gstatic.com/charts/loader.js');
$this->headScript()->captureStart();
echo "
google.charts.load('current', {packages: ['corechart', 'line'], 'language': 'ru'});

google.charts.setOnLoadCallback(drawBasic);

function drawBasic() {
    var data = new google.visualization.DataTable();
    data.addColumn('date', 'X');
    data.addColumn('number', 'metal');
    data.addColumn('number', 'figure');
    data.addRows([".implode(',', $lisChart)."]);
    var options = {
        'height':500,
        'language': 'ru',
        hAxis: {
          title: 'Time'
        },
        vAxis: {
          title: '  '
        }
    };
    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
    chart.draw(data, options);
}
";  
$this->headScript()->captureEnd();
?>
