<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="pull-right"><?=$this->account_BtnChange($this->accountValue)?></div>
                <h3><?=_('Доступный баланс')?>: <?=$this->formatMoney($this->accountValue, true)?></h3>
            </div>  
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <?php
        if (count($this->balances->getBalanceCurrencies())) {
            foreach ($this->balances->getBalanceCurrencies() as $balance) {
                echo '<div class="panel panel-default">';
                echo '<div class="panel-body">';
                    echo '<p>'.$this->escape($balance->getCurrencyName()).' '.$this->cardCurrencyIconBalance($balance).'</p>';
                    echo '<p>'._('Баланс').': '.$this->formatMoney($balance->getValueBalance()).'</p>';
                    echo '<p>'._('Сумма инвестиций').': '.$this->formatMoney($balance->getSumInvest(), true).'</p>';
                    echo '<p>'._('Текущий курс').': '.$this->formatMoney($balance->getValueCurrentCourse(), true).'</p>';
                    echo '<p>'._('Сумма текущей продажи').': '.$this->formatMoney($balance->getSumPay(), true).'</p>';
                echo '</div></div>';
            }
        }
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        if (count($this->balances->getBalanceMetals())) {
            foreach ($this->balances->getBalanceMetals() as $balance) {
                echo '<div class="panel panel-default">';
                echo '<div class="panel-body">';
                    echo '<p>'.$this->escape($balance->getMetalName()).' '.$this->cardMetalIconBalance($balance).'</p>';
                    echo '<p>Баланс: '.$this->formatMoney($balance->getValueBalance()).'</p>';
                    echo '<p>Сумма инвестиций: '.$this->formatMoney($balance->getSumInvest(), true).'</p>';
                    echo '<p>Текущий курс: '.$this->formatMoney($balance->getValueMetalCourse(), true).'</p>';
                    echo '<p>Сумма текущей продажи: '.$this->formatMoney($balance->getSumPay(), true).'</p>';
                echo '</div></div>';
            }
        }
        ?>
    </div>
</div>