<div class="col-sm-6">
    <h2><?=_('Инвестиции в валюту')?></h2>
    <a href="/investments/currency/sub" class="btn btn-default pull-right" role="button"><?=$this->iconSub('sell')?></a>
    <a href="/investments/currency/add" class="btn btn-default pull-right" role="button"><?=$this->iconAdd('pay')?></a>
    <?=$this->investmentCurrency_List($this->investCurrencies)?>
        <!--<span class="pull-right"><a href="/investments/currency/list"><?=_('Показать все')?></a></span>-->
</div>
<div class="col-sm-6">
    <h2><?=_('Инвестиции в металы')?></h2>
    <a href="/investments/metal/sub" class="btn btn-default pull-right" role="button"><?=$this->iconSub('sell')?></a>
    <a href="/investments/metal/add" class="btn btn-default pull-right" role="button"><?=$this->iconAdd('pay')?></a>
    <?=$this->investmentMetal_List($this->investMetals)?>
        <!--<span class="pull-right"><a href="/investments/metal/list"><?=_('Показать все')?></a></span>-->
</div>