<div class="col-sm-6">
    <h3>Инвестиции в валюту</h3>
    <?=$this->investmentCurrency_List($this->investCurrencies)?>
        <span class="pull-right"><a href="/investments/currency/list">Показать все</a></span>
</div>
<div class="col-sm-6">
    <h3>Инвестиции в металы</h3>
    <?=$this->investmentMetal_List($this->investMetals)?>
        <span class="pull-right"><a href="/investments/metal/list">Показать все</a></span>
</div>